version: "3.7"
services:
  nginx-ps:
    image: pagespeed/nginx-pagespeed:stable
    container_name: nginx-ps
    restart: "no"
    depends_on: 
      - wordpress
    ports: 
      - "80:80"
    volumes:
      - type: bind
        source: ./default.conf
        target: /etc/nginx/conf.d/default.conf
      - type: volume
        source: wp-html
        target: /usr/share/nginx/html
  mariadb:
    image: mariadb
    container_name: mariadb
    restart: "no"
    environment:
      MYSQL_ROOT_PASSWORD: "mdb#dpthchrg!"
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: "wp#dpthchrg!"
  wordpress:
    image: wordpress:fpm-alpine
    container_name: wordpress
    restart: "no"
    depends_on: 
      - mariadb
    volumes: 
      - type: volume
        source: php-fpm-config
        target: /usr/local/etc/php-fpm.d
      - type: volume
        source: wp-html
        target: /var/www/html
    environment:
      WORDPRESS_DB_HOST: mariadb
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: "wp#dpthchrg!"
      WORDPRESS_DB_NAME: wordpress
      WORDPRESS_DEBUG: "1"
volumes:
  wp-html:
  nginx-config:
  php-fpm-config:
  
