version: "3.7"
services:
  # nginx-http2:
  #   image: nginx:stable-alpine
  #   container_name: nginx-http2
  #   restart: "no"
  #   depends_on:
  #     - nginx-ps
  #   ports:
  #     - "80:80"    
  #     - "443:443"
  #   volumes:
  #     - type: bind
  #       source: ./proxy.conf
  #       target: /etc/nginx/conf.d/default.conf
  #     - type: bind
  #       source: ./letsencrypt
  #       target: /etc/letsencrypt
  #     - type: volume
  #       source: ssl
  #       target: /etc/ssl
  nginx-ps:
    image: pagespeed/nginx-pagespeed:stable
    container_name: nginx-ps
    restart: always
    depends_on: 
      - wordpress
    ports: 
      - "80:80"
      - "443:443"
    volumes:
      - type: bind
        source: ./nginx.conf
        target: /etc/nginx/conf.d/default.conf
      - type: bind
        source: ./letsencrypt
        target: /etc/letsencrypt
      - type: volume
        source: wp-html
        target: /usr/share/nginx/html
      - type: tmpfs
        target: /var/cache/ngx_pagespeed

  mariadb:
    image: mariadb
    container_name: mariadb
    restart: always
    volumes: 
      - type: volume
        source: mariadb-data
        target: /var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: "mdb#dpthchrg!"
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: "wp#dpthchrg!"
  wordpress:
    image: wordpress:fpm-alpine
    container_name: wordpress
    restart: always
    depends_on: 
      - mariadb
    volumes: 
      - type: bind
        source: ./php.ini
        target: /usr/local/etc/php/php.ini
      # - type: volume
      #   source: php-fpm-config
      #   target: /usr/local/etc/php
      - type: volume
        source: wp-html
        target: /var/www/html
    environment:
      WORDPRESS_DB_HOST: mariadb
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: "wp#dpthchrg!"
      WORDPRESS_DB_NAME: wordpress
      WORDPRESS_DEBUG: "1"
  redis:
    image: redis:alpine
    container_name: redis
    restart: "no"
volumes:
  wp-html:
  nginx-config:
  php-fpm-config:
  mariadb-data:
  letsencrypt:
  ssl:

  # docker run -it -p 80:80 -v $(pwd)/letsencrypt:/etc/letsencrypt certbot/certbot certonly --standalone
  
