version: "3.7"
services:
  nginx-ps:
    image: pagespeed/nginx-pagespeed:stable
    container_name: nginx-ps
    ports: 
      - "80:80"
    volumes:
      - type: volume
        source: nginx-config
        target: /etc/nginx/conf.d/default.conf
      - type: volume
        source: wp-html
        target: /usr/share/nginx/html
  wordpress:
    image: wordpress:fpm-alpine
    container_name: wordpress
    volumes: 
      - type: volume
        source: php-fpm-config
        target: /usr/local/etc/php-fpm.d/www.conf
      - type: volume
        source: wp-html
        target: /var/www/html
volumes:
  wp-html:
  nginx-config:
  php-fpm-config: