version: "3"
services:
  nginx-ps:
    image: pagespeed/nginx-pagespeed:stable
    container_name: nginx-ps
    deploy:
      replicas: 1
    ports: 
      - "80:80"
    volumes:
      - type: bind
        source: ./app/nginx/conf/default.conf
        target: /etc/nginx/conf.d/default.conf
      - type: volume
        source: wordpress
        target: /usr/share/nginx/html
  wordpress:
    image: wordpress:fpm-alpine
    containter_name: wordpress
    deploy:
      replicas: 1
    