version: "3.7"
services:
  nginx-ps:
    image: pagespeed/nginx-pagespeed:stable
    container_name: nginx-ps
    deploy:
      replicas: 1
    ports: 
      - "80:80"
    volumes:
      - type: bind
        source: ./app/nginx/conf/default.conf
        target: /etc/nginx/conf.d/default.conf
    volumes:
      - type: volume
        source: wpdata
        target: /usr/share/nginx/html
  wordpress:
    image: wordpress:fpm-alpine
    container_name: wordpress
    deploy:
      replicas: 1
    volumes: 
      - type: volume
        source: wp-data
        target: /var/www/html
volumes:
  data:
    external: true
    name: wp-data