version: "3.7"
services:
  nginx-http2:
    image: nginx:stable-alpine
    container_name: nginx-http2
    restart: "no"
    depends_on:
      - nginx-ps
    ports:
      - "80:80"    
      - "443:443"
    volumes:
      - type: bind
        source: ./proxy.conf
        target: /etc/nginx/conf.d/default.conf
      - type: bind
        source: ./ssl
        target: /etc/ssl
  nginx-ps:
    image: pagespeed/nginx-pagespeed:stable
    container_name: nginx-ps
    restart: always
    depends_on: 
      - wordpress
    #ports: 
    #  - "80:80"
    volumes:
      - type: bind
        source: ./nginx.conf
        target: /etc/nginx/conf.d/default.conf
      - type: volume
        source: wp-html
        target: /usr/share/nginx/html
  mariadb:
    image: mariadb
    container_name: mariadb
    restart: always
    volumes: 
      - type: volume
        source: mariadb-data
        target: /var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: "mdb#dpthchrg!"
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: "wp#dpthchrg!"
  wordpress:
    image: wordpress:fpm-alpine
    container_name: wordpress
    restart: always
    depends_on: 
      - mariadb
    volumes: 
      - type: volume
        source: php-fpm-config
        target: /usr/local/etc/php-fpm.d
      - type: volume
        source: wp-html
        target: /var/www/html
    environment:
      WORDPRESS_DB_HOST: mariadb
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: "wp#dpthchrg!"
      WORDPRESS_DB_NAME: wordpress
      WORDPRESS_DEBUG: "1"
  redis:
    image: redis:alpine
    container_name: redis
    restart: "no"
volumes:
  wp-html:
  nginx-config:
  php-fpm-config:
  mariadb-data:

  # To get self-signed certficicates run following commands:
  # docker run -it --rm --mount source=./ssl,target=/etc/ssl alpine ash
  # then in the interactive shell run:
  # apk add openssl && openssl req -x509 -nodes -days 365 -newkey rsa:2048 -keyout /etc/ssl/private/nginx.key -out /etc/ssl/certs/nginx.crt
  
